version: '3'
services:
  frontend:
    container_name: frontend-app
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - frontend-app

networks:
  frontend-app:
    driver: bridge
